#!/bin/bash
#PBS -P CFP01-CF-060
#PBS -j oe
#PBS -k oed
#PBS -N llm-latent-cloze
#PBS -M e1583535@u.nus.edu
#PBS -q auto
#PBS -m abe
#PBS -l select=1:ngpus=2
#PBS -l walltime=96:00:00

cd $PBS_O_WORKDIR;

image="/app1/common/singularity-img/hopper/pytorch/pytorch_2.3.0_cuda_12.4_ngc_24.04.sif"

module load singularity

LOG_DIR=./logs/clozes
mkdir -p $LOG_DIR

singularity exec -e \
--env HF_HOME=/scratch/e1583535/cache \
--env HF_DATASETS_CACHE=/scratch/e1583535/cache/datasets \
$image bash << EOF > $LOG_DIR/stdout.$PBS_JOBID.log 2> $LOG_DIR/stderr.$PBS_JOBID.log

python -c "import gc, torch; torch.cuda.empty_cache(); gc.collect()"

source /hpctmp/e1583535/virtualenvs/lm-latent/bin/activate

echo "Starting training at $(date)"
echo "Running on host: $(hostname)"
echo "GPU info:"
nvidia-smi --query-gpu=name,memory.total,memory.free --format=csv,noheader,nounits || echo "No GPU detected"

python cloze_olmo2.py \
  --target_lang zh \
  --model $MODEL_PATH \
  --data_prefix /scratch/e1583535/llm-latent-language/data/langs/ \
  --out_dir /scratch/e1583535/llm-latent-language/visuals \
  --key blank_prompt_translation_masked \
  --img_ext png \
  --no_load_in_8bit

# you can put more commands here
echo "Done"

EOF